# Configurazione del Sito
title: Narshe Mines
email: somemail@mail.com
author: Andrea Corinti
description: Breve descrizione del sito
url:

# Collection / Autori

collections:
  authors:
    output: true
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Logo
logo: "/assets/immagini/logo.png" # idealmente, 150x150px

# Build settings
permalink: :title/
sass:
  sass_dir: /css

# Social
show_social_icons: true
github: github
facebook: github
instagram: github
twitter: github

# Plugin
plugins:
  - jekyll-paginate

# Paginate
paginate: 3 # imposta il numero di news visibili nella home
